name: ui_kit
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  icon_font_generator: ^4.1.0
  logger_helper:
    git:
      url: https://gitea.intelligent-system.ru/train2026/Prof_26_Zahar.git
      ref: 30-03-26/1/logger_helper

publish_to: none

icon_font:
  input_svg_dir: assets/icons/
  output_font_file: assets/fonts/CustomIconFont.otf

  output_class_file: lib/src/presentation/typography/custom_icons.dart
  class_name: CustomIcons
  package: ui_kit
  format: true

  font_name: CustomIconFont
  verbose: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  fonts:
    - family: CustomIconFont
      fonts:
        - asset: assets/fonts/CustomIconFont.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
  assets:
    - assets/icons/